* Тестовое задание No1 

** Задание

*** Описание

Необходимо написать веб приложение для получения информации с сайта
n.ru. На главной странице находится форма поиска с диапазоном комнат,
ценой и множественным выбором станций метро. После заполнения этих
полей происходит вывод результатов поиска на экран.  Данные нужно
получать только с первой страницы.  Использование функций не
допускается (только ООП). Объявление – объект с набором свойств. На
странице результатов сверху отображается заполненная форма поиска с
возможностью изменения параметров поиска. Поиск должен работать как с
включенным Javascript’ом, так и без него. При включенном Javascript’e
результаты поиска должны подгружаться с помощью AJAX.  Список станций
метрополитена подгружается с поисковой формы bn.ru один раз (например,
возможно реализовать кеширование в файл), далее работаем с локальной
закешированной версией списка.  Источник данных
http://www.bn.ru/zap_fl.phtml

*** Форма 

- Количество комнат: поля от и до
- Цена: поля от и до 
- Станции метро: множественный выбор из списка станций метро
- Кнопка «Найти» 

*** Поля поисковой выдачи

- Издание
- Количество комнат
- Адрес
- Метро
- Этаж 
- Тип дома 
- Площадь (общая, жилая, кухня)
- Телефон
- Санузел
- Субъект
- Контакт
- Доп. сведения

*** Используемые технологии 

- Python 
- JQuery
  
** Текущее TODO

*** DONE Закачка станций метро из формы bn
*** TODO Получение квартир с bn.ru

Запрос:
http://www.bn.ru/zap_fl.phtml?kkv1=1&kkv2=2&price1=2000&price2=3000&so1=&so2=&sk1=&sk2=&type[]=1&sorttype=0&sort_ord=0&metro[]=86&text=

Достаточный запрос:

http://www.bn.ru/zap_fl.phtml?kkv1=1&kkv2=2&price1=2000&price2=3000&metro[]=118&metro[]=84

kkv_1=1
kkv_2=2
price1=2000
price2=3000
metro[]=118&metro[]=84

*** TODO Ajax вывод 
    
